//CHARACTERS
export const CHARACTER_LOADING = "CHARACTER_LOADING";
export const CHARACTER_SUCCESS = "CHARACTER_SUCCESS";
export const CHARACTER_FAILURE = "CHARACTER_FAILURE";
export const CHARACTER_DETAIL_LOADING = "CHARACTER_DETAIL_LOADING";
export const CHARACTER_DETAIL_SUCCESS = "CHARACTER_DETAIL_SUCCESS";
export const CHARACTER_DETAIL_FAILURE = "CHARACTER_DETAIL_FAILURE";
//LOCATIONS
export const LOCATION_LOADING = "LOCATION_LOADING";
export const LOCATION_SUCCESS = "LOCATION_SUCCESS";
export const LOCATION_FAILURE = "LOCATION_FAILURE";
export const DETAIL_LOCATION_LOADING = "DETAIL_LOCATION_LOADING";
export const DETAIL_LOCATION_SUCCESS = "DETAIL_LOCATION_SUCCESS";
export const DETAIL_LOCATION_FAILURE = "DETAIL_LOCATION_FAILURE";
//EPISODES
export const EPISODE_LOADING = "EPISODE_LOADING";
export const EPISODE_SUCCESS = "EPISODE_SUCCESS";
export const EPISODE_FAILURE = "EPISODE_FAILURE";
export const DETAIL_EPISODE_LOADING = "DETAIL_EPISODE_LOADING";
export const DETAIL_EPISODE_SUCCESS = "DETAIL_EPISODE_SUCCESS";
export const DETAIL_EPISODE_FAILURE = "DETAIL_EPISODE_FAILURE";